---
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb
      ansible.builtin.yum:
        name: mariadb
        state: present

    - name: Install Python MySQL dependencies
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start mariadb-server service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Start mariadb-server service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'dbName'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock


    - name: Create database user with name 'userName'
      community.mysql.mysql_user:
        name: vprofile
        password: setPasswd
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

