---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on centos
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install ntp agent on Ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

# WHEN conditon works like if else condition, in this case is checking system dystriptuion to run task depending if its yum for CentOS or apt for Ubuntu.\

    - name: Start service on centos
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Starte service on ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

